# Generated by Django 3.1.7 on 2021-03-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
