# Generated by Django 3.1.7 on 2021-03-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210319_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='display_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
